/*
 * pinout.h
 *
 * Created: 02/01/2018 17:13:50
 *  Author: Piotr
 */ 


#ifndef PINOUT_H_
#define PINOUT_H_

#define DCLK_OUT_PIN EXT1_PWM_0_PIN
#define DCLK_OUT_MUX EXT1_PWM_0_MUX
#define HSYNC_OUT_PIN EXT3_PWM_0_PIN
#define HSYNC_OUT_MUX EXT3_PWM_0_MUX
#define VSYNC_OUT_PIN PIN_PB30E_TCC0_WO0
#define VSYNC_OUT_MUX MUX_PB30E_TCC0_WO0
//#define VSYNC_OUT_PIN PIN_PA21E_TC3_WO1
//#define VSYNC_OUT_MUX MUX_PA21E_TC3_WO1

#define PWM_MODULE   EXT1_PWM_MODULE
#define PWM_MODULE_1 EXT3_PWM_MODULE
#define PWM_MODULE_2 TCC0
//#define PWM_MODULE_2 TC3

#define DE_PIN PIN_PA02 // Data Enable Pin
#define HSYNC_PIN PIN_PB02 // HSYNC Pin



#endif /* PINOUT_H_ */